name: CI

on:
  push:
    branches: [next]
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
        runner: [ubuntu-latest, windows-latest, macos-14]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-14
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Install Rust
      - name: Install Rust (Stable)
        run: rustup default stable

      - name: Setup rust target
        run: rustup target add ${{ matrix.target }}

      # Cache cargo if Rust
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Cache the `oxide` Rust build if Rust is required
      - name: Cache oxide build
        uses: actions/cache@v4
        with:
          path: |
            ./target/
            ./crates/node/*.node
            ./crates/node/index.js
            ./crates/node/index.d.ts
          key: ${{ runner.os }}-oxide-${{ hashFiles('./crates/**/*') }}

      # Nx Cloud start-ci-run
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="test:ui"

      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'next'

      # Nx Affected command build
      - name: Run affected for test and build
        run: npx nx affected --target=build --parallel=3 --exclude=nextjs-playground,vite-playground

      - name: Lint
        run: npx nx affected --target=lint
        # Only lint on linux to avoid \r\n line ending errors
        if: matrix.runner == 'ubuntu-latest'

      # Playwright setup and tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx nx affected -t test:ui

      # Nx Affected command for tests
      - name: Run affected for tests
        run: npx nx affected --target=test --parallel=3

      # Nx Affected command for integration tests
      - name: Run affected for tests
        run: npx nx affected --target=integration-test --parallel=3
